// Curated from public/assets/Portfolio+2023_online.pdf. Page images are generated by
// scripts/render-portfolio.py — keep the page numbers here and in that script in sync.

const base = import.meta.env.BASE_URL

export const portfolioPdf = `${base}assets/Portfolio+2023_online.pdf`

export const pageImage = (number, size = '') => `${base}portfolio/pages/p${String(number).padStart(2, '0')}${size}.webp`

export const collections = [
  {
    id: 'direct-mail',
    title: 'Direct Mail & Newsletters',
    short: 'Direct mail',
    kicker: 'Printed, personalized, posted',
    blurb: 'Letters, postcards, newsletters, and EDDM drops—personalized with variable data, inserted, and mailed without leaving the building.',
    color: 'cyan',
    photo: `${base}portfolio/photos/mailroom.webp`,
    photoAlt: 'Addressed envelopes feeding through a mail inserter',
    service: 'mailing',
    pages: [
      {
        number: 6,
        projects: [
          { client: 'Pioneer Public Television', pieces: ['Member drive'], specs: '70# Cougar Text letter · #10 window envelope · #9 reply envelope · 110# Index VDP reply card', tags: ['Direct mail', 'Variable data'] },
          { client: 'Lyon County Fair', pieces: ['Schedule & events EDDM postcard'], tags: ['Direct mail', 'EDDM'] },
        ],
      },
      {
        number: 5,
        projects: [
          { client: 'Prairie Home Hospice', pieces: ['Newsletter'], tags: ['Newsletters'] },
          { client: 'Minnwest Bank', pieces: ['Skip-a-Payment letter'], specs: '70# Cougar Text VDP letter · regular window envelope', tags: ['Direct mail', 'Variable data'] },
          { client: 'Olivia Hospital & Clinic', pieces: ['VDP postcard'], tags: ['Direct mail', 'Variable data'] },
        ],
      },
      {
        number: 7,
        projects: [
          { client: 'New London-Spicer School District', pieces: ['EDDM school calendar'], tags: ['EDDM'] },
          { client: 'Minnwest Bank', pieces: ['Prime Club newsletter'], tags: ['Newsletters'] },
          { client: 'Runnings', pieces: ['Corporate newsletter'], tags: ['Newsletters'] },
        ],
      },
    ],
  },
  {
    id: 'identity',
    title: 'Brand Identity & Stationery',
    short: 'Identity',
    kicker: 'First impressions, matched',
    blurb: 'Letterhead, envelopes, business cards, and pocket folders designed as one family—so a business looks established the moment it hands something over.',
    color: 'coral',
    photo: `${base}portfolio/photos/cutter.webp`,
    photoAlt: 'A hand squaring a stack of freshly printed sheets on a paper cutter',
    service: 'design',
    pages: [
      {
        number: 13,
        projects: [
          { client: 'Northwestern Farm Management Co.', pieces: ['Letterhead', '#10 envelope', 'Business card', 'Pocket folder', 'Postcard', '13 × 10 envelope'], tags: ['Letterhead & envelopes', 'Business cards', 'Pocket folders'] },
        ],
      },
      {
        number: 12,
        projects: [
          { client: 'Helena', pieces: ['Pocket folder', 'Notepads'], tags: ['Pocket folders'] },
          { client: 'Sussner Construction', pieces: ['Letterhead', '#10 envelope', 'Business card', 'Pocket folder'], tags: ['Letterhead & envelopes', 'Business cards', 'Pocket folders'] },
        ],
      },
      {
        number: 11,
        projects: [
          { client: 'Shrimp Shop', pieces: ['Business card'], tags: ['Business cards'] },
          { client: 'Southwest Minnesota Private Industry Council', pieces: ['Letterhead', '#10 envelope'], tags: ['Letterhead & envelopes'] },
          { client: 'Wilson O’Brien Realtors', pieces: ['Business card', 'Holiday postcard'], tags: ['Business cards', 'Direct mail'] },
        ],
      },
    ],
  },
  {
    id: 'community',
    title: 'Schools, Events & Community',
    short: 'Community',
    kicker: 'For the whole region',
    blurb: 'Programs, posters, banners, tickets, and guides for the schools, causes, and celebrations that keep southwest Minnesota busy.',
    color: 'gold',
    photo: `${base}portfolio/photos/press.webp`,
    photoAlt: 'Full-color sheets stacking at the delivery end of a press',
    service: 'offset',
    pages: [
      {
        number: 20,
        projects: [
          { client: 'Marshall High School', pieces: ['Sport programs', 'Vinyl banners', 'Theater posters', 'Event tickets', 'Shirt (design only)'], tags: ['Posters & programs', 'Signs & banners', 'Tickets & certificates'] },
        ],
      },
      {
        number: 21,
        projects: [
          { client: 'St. Edwards Catholic School', pieces: ['Fundraiser program', 'Fundraiser ticket'], tags: ['Posters & programs', 'Tickets & certificates'] },
          { client: 'Southwest Minnesota State University', pieces: ['Die-cut Mustang flyer'], tags: ['Posters & programs', 'Die-cut & specialty'] },
          { client: 'Henle Printing', pieces: ['Corrugated graduation yard signs'], tags: ['Signs & banners'] },
        ],
      },
      {
        number: 18,
        projects: [
          { client: 'Buffalo Ridge Chapter, ABATE of Minnesota', pieces: ['Event posters', 'Numbered tickets'], tags: ['Posters & programs', 'Tickets & certificates'] },
          { client: 'City of Marshall', pieces: ['Area community guide book'], tags: ['Catalogs & guides'] },
          { client: 'Hy-Vee', pieces: ['Pharmacy magnet'], tags: ['Die-cut & specialty'] },
        ],
      },
    ],
  },
  {
    id: 'specialty',
    title: 'Promotions, Tickets & Specialty',
    short: 'Specialty',
    kicker: 'Odd shapes welcome',
    blurb: 'Die-cut stickers, numbered raffle tickets, door hangers, scratch-offs, and catalogs—the jobs that need a little more than ink on a sheet.',
    color: 'navy',
    photo: `${base}portfolio/photos/finishing.webp`,
    photoAlt: 'Printed pieces stacking out of a finishing machine',
    service: 'finishing',
    pages: [
      {
        number: 17,
        projects: [
          { client: 'United Way', pieces: ['Children’s Go Fish cards'], tags: ['Die-cut & specialty'] },
          { client: 'Marshall Radio', pieces: ['Solar eclipse glasses (design only)', 'Summer Coke event scratch-off'], tags: ['Die-cut & specialty', 'Tickets & certificates'] },
        ],
      },
      {
        number: 19,
        projects: [
          { client: 'Tall Grass Liquor', pieces: ['Carton sticker'], tags: ['Die-cut & specialty'] },
          { client: 'Downtown Sound', pieces: ['Pub crawl passport'], tags: ['Tickets & certificates'] },
          { client: 'Marshall Municipal Utilities', pieces: ['Door hanger'], tags: ['Door hangers & tags'] },
          { client: 'Cliff Viessman, Inc.', pieces: ['Perforated service tag'], tags: ['Door hangers & tags'] },
        ],
      },
      {
        number: 23,
        projects: [
          { client: 'VIP Greenhouse', pieces: ['Product catalog'], tags: ['Catalogs & guides'] },
          { client: 'Lake Hendricks Fishing Derby', pieces: ['Numbered raffle ticket'], tags: ['Tickets & certificates'] },
          { client: 'Rotary Club', pieces: ['Duck Race fundraiser raffle ticket'], tags: ['Tickets & certificates'] },
          { client: 'Lyon County Environmental Center', pieces: ['Recycling bin sticker'], tags: ['Die-cut & specialty'] },
          { client: 'Salfer’s Food Center', pieces: ['Gift certificate'], tags: ['Tickets & certificates'] },
        ],
      },
    ],
  },
]

// Flattened, in viewing order, with ids for linking straight to a page or project.
export const pages = collections.flatMap((collection) =>
  collection.pages.map((page) => ({
    ...page,
    collection,
    projects: page.projects.map((project, index) => ({ ...project, id: `p${page.number}-${index + 1}` })),
  })),
)

const industryByClient = {
  'Pioneer Public Television': 'Nonprofit & events',
  'Lyon County Fair': 'Nonprofit & events',
  'Prairie Home Hospice': 'Healthcare',
  'Minnwest Bank': 'Banking & finance',
  'Olivia Hospital & Clinic': 'Healthcare',
  'New London-Spicer School District': 'Education',
  'Runnings': 'Retail & hospitality',
  'Northwestern Farm Management Co.': 'Business & agriculture',
  'Helena': 'Business & agriculture',
  'Sussner Construction': 'Business & agriculture',
  'Shrimp Shop': 'Retail & hospitality',
  'Southwest Minnesota Private Industry Council': 'Community & government',
  'Wilson O’Brien Realtors': 'Business & agriculture',
  'Marshall High School': 'Education',
  'St. Edwards Catholic School': 'Education',
  'Southwest Minnesota State University': 'Education',
  'Henle Printing': 'Business & agriculture',
  'Buffalo Ridge Chapter, ABATE of Minnesota': 'Nonprofit & events',
  'City of Marshall': 'Community & government',
  'Hy-Vee': 'Retail & hospitality',
  'United Way': 'Nonprofit & events',
  'Marshall Radio': 'Business & agriculture',
  'Tall Grass Liquor': 'Retail & hospitality',
  'Downtown Sound': 'Retail & hospitality',
  'Marshall Municipal Utilities': 'Community & government',
  'Cliff Viessman, Inc.': 'Business & agriculture',
  'VIP Greenhouse': 'Retail & hospitality',
  'Lake Hendricks Fishing Derby': 'Nonprofit & events',
  'Rotary Club': 'Nonprofit & events',
  'Lyon County Environmental Center': 'Community & government',
  'Salfer’s Food Center': 'Retail & hospitality',
}

export const projects = pages.flatMap((page) => page.projects.map((project) => ({ ...project, industry: industryByClient[project.client] || 'Business & agriculture', page })))

export const industries = [...new Set(projects.map((p) => p.industry))]
  .map((industry) => ({ industry, count: projects.filter((p) => p.industry === industry).length }))
  .sort((a, b) => b.count - a.count)

export const clientCount = new Set(projects.filter((p) => p.client !== 'Henle Printing').map((p) => p.client)).size

export const tags = [...new Set(projects.flatMap((p) => p.tags))]
  .map((tag) => ({ tag, count: projects.filter((p) => p.tags.includes(tag)).length }))
  .sort((a, b) => b.count - a.count)
